/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.ProductDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * An item in a shopping cart.
 */
@JsonPropertyOrder({
  CartItem.JSON_PROPERTY_INDEX,
  CartItem.JSON_PROPERTY_PRODUCT,
  CartItem.JSON_PROPERTY_QUANTITY,
  CartItem.JSON_PROPERTY_TOTAL,
  CartItem.JSON_PROPERTY_DISCOUNT,
  CartItem.JSON_PROPERTY_COUPON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class CartItem {
  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nonnull
  private Integer index;

  public static final String JSON_PROPERTY_PRODUCT = "product";
  @javax.annotation.Nonnull
  private ProductDetails product;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nonnull
  private Integer quantity;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nonnull
  private Double total;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  @javax.annotation.Nullable
  private Double discount;

  public static final String JSON_PROPERTY_COUPON = "coupon";
  @javax.annotation.Nullable
  private String coupon;

  public CartItem() { 
  }

  public CartItem index(@javax.annotation.Nonnull Integer index) {
    this.index = index;
    return this;
  }

  /**
   * The index, starting from zero, representing the order in which the item was added to the shopping cart.
   * @return index
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndex(@javax.annotation.Nonnull Integer index) {
    this.index = index;
  }


  public CartItem product(@javax.annotation.Nonnull ProductDetails product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRODUCT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProductDetails getProduct() {
    return product;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProduct(@javax.annotation.Nonnull ProductDetails product) {
    this.product = product;
  }


  public CartItem quantity(@javax.annotation.Nonnull Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * The number of units of the item in the shopping cart.
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(@javax.annotation.Nonnull Integer quantity) {
    this.quantity = quantity;
  }


  public CartItem total(@javax.annotation.Nonnull Double total) {
    this.total = total;
    return this;
  }

  /**
   * The total for the item. It includes discounts and any other adjustment.
   * @return total
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@javax.annotation.Nonnull Double total) {
    this.total = total;
  }


  public CartItem discount(@javax.annotation.Nullable Double discount) {
    this.discount = discount;
    return this;
  }

  /**
   * The amount of the discount applied to the item.
   * @return discount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getDiscount() {
    return discount;
  }


  @JsonProperty(value = JSON_PROPERTY_DISCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDiscount(@javax.annotation.Nullable Double discount) {
    this.discount = discount;
  }


  public CartItem coupon(@javax.annotation.Nullable String coupon) {
    this.coupon = coupon;
    return this;
  }

  /**
   * The coupon applied to the item. For example, \&quot;SUPER_DEALS\&quot;.
   * @return coupon
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUPON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCoupon() {
    return coupon;
  }


  @JsonProperty(value = JSON_PROPERTY_COUPON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoupon(@javax.annotation.Nullable String coupon) {
    this.coupon = coupon;
  }


  /**
   * Return true if this CartItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartItem {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    coupon: ").append(toIndentedString(coupon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

