/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.croct.client.export.model.DeviceCategory;
import com.croct.client.export.model.OperatingSystem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * The available information about a device.
 */
@JsonPropertyOrder({
  Device.JSON_PROPERTY_NAME,
  Device.JSON_PROPERTY_VENDOR,
  Device.JSON_PROPERTY_CATEGORY,
  Device.JSON_PROPERTY_OPERATING_SYSTEM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Device {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_VENDOR = "vendor";
  @javax.annotation.Nullable
  private String vendor;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  @javax.annotation.Nonnull
  private DeviceCategory category;

  public static final String JSON_PROPERTY_OPERATING_SYSTEM = "operatingSystem";
  @javax.annotation.Nonnull
  private OperatingSystem operatingSystem;

  public Device() { 
  }

  public Device name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the device, non-empty. For example, \&quot;Mac\&quot;, \&quot;iPhone\&quot; or \&quot;Nexus 10\&quot;.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Device vendor(@javax.annotation.Nullable String vendor) {
    this.vendor = vendor;
    return this;
  }

  /**
   * The vendor of the device, non-empty. For example, \&quot;Apple\&quot;, \&quot;Samsung\&quot; or \&quot;LG\&quot;.
   * @return vendor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVendor() {
    return vendor;
  }


  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVendor(@javax.annotation.Nullable String vendor) {
    this.vendor = vendor;
  }


  public Device category(@javax.annotation.Nonnull DeviceCategory category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DeviceCategory getCategory() {
    return category;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategory(@javax.annotation.Nonnull DeviceCategory category) {
    this.category = category;
  }


  public Device operatingSystem(@javax.annotation.Nonnull OperatingSystem operatingSystem) {
    this.operatingSystem = operatingSystem;
    return this;
  }

  /**
   * Get operatingSystem
   * @return operatingSystem
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPERATING_SYSTEM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OperatingSystem getOperatingSystem() {
    return operatingSystem;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATING_SYSTEM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperatingSystem(@javax.annotation.Nonnull OperatingSystem operatingSystem) {
    this.operatingSystem = operatingSystem;
  }


  /**
   * Return true if this Device object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Device {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    operatingSystem: ").append(toIndentedString(operatingSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

