/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * EventResponseMetadata
 */
@JsonPropertyOrder({
  EventResponseMetadata.JSON_PROPERTY_ORGANIZATION_NAME,
  EventResponseMetadata.JSON_PROPERTY_ORGANIZATION_SLUG,
  EventResponseMetadata.JSON_PROPERTY_WORKSPACE_NAME,
  EventResponseMetadata.JSON_PROPERTY_WORKSPACE_SLUG,
  EventResponseMetadata.JSON_PROPERTY_APPLICATION_NAME,
  EventResponseMetadata.JSON_PROPERTY_APPLICATION_SLUG
})
@JsonTypeName("EventResponse_metadata")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0-SNAPSHOT")
public class EventResponseMetadata {
  public static final String JSON_PROPERTY_ORGANIZATION_NAME = "organizationName";
  private String organizationName;

  public static final String JSON_PROPERTY_ORGANIZATION_SLUG = "organizationSlug";
  private String organizationSlug;

  public static final String JSON_PROPERTY_WORKSPACE_NAME = "workspaceName";
  private String workspaceName;

  public static final String JSON_PROPERTY_WORKSPACE_SLUG = "workspaceSlug";
  private String workspaceSlug;

  public static final String JSON_PROPERTY_APPLICATION_NAME = "applicationName";
  private String applicationName;

  public static final String JSON_PROPERTY_APPLICATION_SLUG = "applicationSlug";
  private String applicationSlug;

  public EventResponseMetadata() { 
  }

  public EventResponseMetadata organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganizationName() {
    return organizationName;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }


  public EventResponseMetadata organizationSlug(String organizationSlug) {
    this.organizationSlug = organizationSlug;
    return this;
  }

   /**
   * Get organizationSlug
   * @return organizationSlug
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganizationSlug() {
    return organizationSlug;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationSlug(String organizationSlug) {
    this.organizationSlug = organizationSlug;
  }


  public EventResponseMetadata workspaceName(String workspaceName) {
    this.workspaceName = workspaceName;
    return this;
  }

   /**
   * Get workspaceName
   * @return workspaceName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORKSPACE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkspaceName() {
    return workspaceName;
  }


  @JsonProperty(JSON_PROPERTY_WORKSPACE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkspaceName(String workspaceName) {
    this.workspaceName = workspaceName;
  }


  public EventResponseMetadata workspaceSlug(String workspaceSlug) {
    this.workspaceSlug = workspaceSlug;
    return this;
  }

   /**
   * Get workspaceSlug
   * @return workspaceSlug
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORKSPACE_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkspaceSlug() {
    return workspaceSlug;
  }


  @JsonProperty(JSON_PROPERTY_WORKSPACE_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkspaceSlug(String workspaceSlug) {
    this.workspaceSlug = workspaceSlug;
  }


  public EventResponseMetadata applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLICATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getApplicationName() {
    return applicationName;
  }


  @JsonProperty(JSON_PROPERTY_APPLICATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }


  public EventResponseMetadata applicationSlug(String applicationSlug) {
    this.applicationSlug = applicationSlug;
    return this;
  }

   /**
   * Get applicationSlug
   * @return applicationSlug
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLICATION_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getApplicationSlug() {
    return applicationSlug;
  }


  @JsonProperty(JSON_PROPERTY_APPLICATION_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicationSlug(String applicationSlug) {
    this.applicationSlug = applicationSlug;
  }


  /**
   * Return true if this EventResponse_metadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventResponseMetadata eventResponseMetadata = (EventResponseMetadata) o;
    return Objects.equals(this.organizationName, eventResponseMetadata.organizationName) &&
        Objects.equals(this.organizationSlug, eventResponseMetadata.organizationSlug) &&
        Objects.equals(this.workspaceName, eventResponseMetadata.workspaceName) &&
        Objects.equals(this.workspaceSlug, eventResponseMetadata.workspaceSlug) &&
        Objects.equals(this.applicationName, eventResponseMetadata.applicationName) &&
        Objects.equals(this.applicationSlug, eventResponseMetadata.applicationSlug);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationName, organizationSlug, workspaceName, workspaceSlug, applicationName, applicationSlug);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventResponseMetadata {\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    organizationSlug: ").append(toIndentedString(organizationSlug)).append("\n");
    sb.append("    workspaceName: ").append(toIndentedString(workspaceName)).append("\n");
    sb.append("    workspaceSlug: ").append(toIndentedString(workspaceSlug)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationSlug: ").append(toIndentedString(applicationSlug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

