/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * EventResponseMetadata
 */
@JsonPropertyOrder({
  EventResponseMetadata.JSON_PROPERTY_ORGANIZATION_NAME,
  EventResponseMetadata.JSON_PROPERTY_ORGANIZATION_SLUG,
  EventResponseMetadata.JSON_PROPERTY_WORKSPACE_NAME,
  EventResponseMetadata.JSON_PROPERTY_WORKSPACE_SLUG,
  EventResponseMetadata.JSON_PROPERTY_APPLICATION_NAME,
  EventResponseMetadata.JSON_PROPERTY_APPLICATION_SLUG
})
@JsonTypeName("EventResponse_metadata")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class EventResponseMetadata {
  public static final String JSON_PROPERTY_ORGANIZATION_NAME = "organizationName";
  @javax.annotation.Nonnull
  private String organizationName;

  public static final String JSON_PROPERTY_ORGANIZATION_SLUG = "organizationSlug";
  @javax.annotation.Nonnull
  private String organizationSlug;

  public static final String JSON_PROPERTY_WORKSPACE_NAME = "workspaceName";
  @javax.annotation.Nonnull
  private String workspaceName;

  public static final String JSON_PROPERTY_WORKSPACE_SLUG = "workspaceSlug";
  @javax.annotation.Nonnull
  private String workspaceSlug;

  public static final String JSON_PROPERTY_APPLICATION_NAME = "applicationName";
  @javax.annotation.Nonnull
  private String applicationName;

  public static final String JSON_PROPERTY_APPLICATION_SLUG = "applicationSlug";
  @javax.annotation.Nonnull
  private String applicationSlug;

  public EventResponseMetadata() { 
  }

  public EventResponseMetadata organizationName(@javax.annotation.Nonnull String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * Get organizationName
   * @return organizationName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganizationName() {
    return organizationName;
  }


  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationName(@javax.annotation.Nonnull String organizationName) {
    this.organizationName = organizationName;
  }


  public EventResponseMetadata organizationSlug(@javax.annotation.Nonnull String organizationSlug) {
    this.organizationSlug = organizationSlug;
    return this;
  }

  /**
   * Get organizationSlug
   * @return organizationSlug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganizationSlug() {
    return organizationSlug;
  }


  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationSlug(@javax.annotation.Nonnull String organizationSlug) {
    this.organizationSlug = organizationSlug;
  }


  public EventResponseMetadata workspaceName(@javax.annotation.Nonnull String workspaceName) {
    this.workspaceName = workspaceName;
    return this;
  }

  /**
   * Get workspaceName
   * @return workspaceName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkspaceName() {
    return workspaceName;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkspaceName(@javax.annotation.Nonnull String workspaceName) {
    this.workspaceName = workspaceName;
  }


  public EventResponseMetadata workspaceSlug(@javax.annotation.Nonnull String workspaceSlug) {
    this.workspaceSlug = workspaceSlug;
    return this;
  }

  /**
   * Get workspaceSlug
   * @return workspaceSlug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkspaceSlug() {
    return workspaceSlug;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkspaceSlug(@javax.annotation.Nonnull String workspaceSlug) {
    this.workspaceSlug = workspaceSlug;
  }


  public EventResponseMetadata applicationName(@javax.annotation.Nonnull String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

  /**
   * Get applicationName
   * @return applicationName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APPLICATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getApplicationName() {
    return applicationName;
  }


  @JsonProperty(value = JSON_PROPERTY_APPLICATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicationName(@javax.annotation.Nonnull String applicationName) {
    this.applicationName = applicationName;
  }


  public EventResponseMetadata applicationSlug(@javax.annotation.Nonnull String applicationSlug) {
    this.applicationSlug = applicationSlug;
    return this;
  }

  /**
   * Get applicationSlug
   * @return applicationSlug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APPLICATION_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getApplicationSlug() {
    return applicationSlug;
  }


  @JsonProperty(value = JSON_PROPERTY_APPLICATION_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicationSlug(@javax.annotation.Nonnull String applicationSlug) {
    this.applicationSlug = applicationSlug;
  }


  /**
   * Return true if this EventResponse_metadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventResponseMetadata {\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    organizationSlug: ").append(toIndentedString(organizationSlug)).append("\n");
    sb.append("    workspaceName: ").append(toIndentedString(workspaceName)).append("\n");
    sb.append("    workspaceSlug: ").append(toIndentedString(workspaceSlug)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationSlug: ").append(toIndentedString(applicationSlug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

