/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.EventContext;
import com.croct.client.export.model.EventPayload;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * Event
 */
@JsonPropertyOrder({
  Event.JSON_PROPERTY_EVENT_ID,
  Event.JSON_PROPERTY_SESSION_ID,
  Event.JSON_PROPERTY_USER_ID,
  Event.JSON_PROPERTY_TIMESTAMP,
  Event.JSON_PROPERTY_SYSTEM_TIMESTAMP,
  Event.JSON_PROPERTY_CONTEXT,
  Event.JSON_PROPERTY_PAYLOAD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0-SNAPSHOT")
public class Event {
  public static final String JSON_PROPERTY_EVENT_ID = "eventId";
  @javax.annotation.Nonnull
  private String eventId;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nonnull
  private UUID sessionId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nonnull
  private UUID userId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nonnull
  private Long timestamp;

  public static final String JSON_PROPERTY_SYSTEM_TIMESTAMP = "systemTimestamp";
  @javax.annotation.Nonnull
  private Long systemTimestamp;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @javax.annotation.Nullable
  private EventContext context;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @javax.annotation.Nonnull
  private EventPayload payload;

  public Event() { 
  }

  public Event eventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * The unique identifier of the event.
   * @return eventId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEventId() {
    return eventId;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
  }


  public Event sessionId(@javax.annotation.Nonnull UUID sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * The ID of the session assigned to the event.
   * @return sessionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionId(@javax.annotation.Nonnull UUID sessionId) {
    this.sessionId = sessionId;
  }


  public Event userId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The internal ID of the user who originated the event.
   * @return userId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
  }


  public Event timestamp(@javax.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The timestamp when the event was tracked, in milliseconds since epoch.
   * @return timestamp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@javax.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
  }


  public Event systemTimestamp(@javax.annotation.Nonnull Long systemTimestamp) {
    this.systemTimestamp = systemTimestamp;
    return this;
  }

  /**
   * The timestamp when the event was ingested by the system, in milliseconds since epoch.
   * @return systemTimestamp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SYSTEM_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSystemTimestamp() {
    return systemTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_SYSTEM_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSystemTimestamp(@javax.annotation.Nonnull Long systemTimestamp) {
    this.systemTimestamp = systemTimestamp;
  }


  public Event context(@javax.annotation.Nullable EventContext context) {
    this.context = context;
    return this;
  }

  /**
   * Get context
   * @return context
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EventContext getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContext(@javax.annotation.Nullable EventContext context) {
    this.context = context;
  }


  public Event payload(@javax.annotation.Nonnull EventPayload payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Get payload
   * @return payload
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EventPayload getPayload() {
    return payload;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayload(@javax.annotation.Nonnull EventPayload payload) {
    this.payload = payload;
  }


  /**
   * Return true if this Event object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    systemTimestamp: ").append(toIndentedString(systemTimestamp)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

