/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets EventType
 */
public enum EventType {
  
  USER_SIGNED_UP("userSignedUp"),
  
  USER_SIGNED_IN("userSignedIn"),
  
  USER_SIGNED_OUT("userSignedOut"),
  
  TAB_OPENED("tabOpened"),
  
  TAB_URL_CHANGED("tabUrlChanged"),
  
  TAB_VISIBILITY_CHANGED("tabVisibilityChanged"),
  
  LOCATION_DETECTED("locationDetected"),
  
  CLIENT_DETECTED("clientDetected"),
  
  PAGE_OPENED("pageOpened"),
  
  PAGE_LOADED("pageLoaded"),
  
  PRODUCT_VIEWED("productAbandoned"),
  
  CART_VIEWED("productViewed"),
  
  CART_MODIFIED("cartAbandoned"),
  
  CHECKOUT_STARTED("cartViewed"),
  
  ORDER_PLACED("cartModified"),
  
  TEST_GROUP_ASSIGNED("checkoutStarted"),
  
  NOTHING_CHANGED("orderPlaced"),
  
  GOAL_COMPLETED("nothingChanged"),
  
  EVENT_OCCURRED("goalCompleted"),
  
  SLOT_PERSONALIZED("eventOccurred"),
  
  LEAD_GENERATED("slotPersonalized"),
  
  AUDIENCE_MATCHED("leadGenerated"),
  
  AUDIENCE_MATCHED("audienceMatched");

  private String value;

  EventType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EventType fromValue(String value) {
    for (EventType b : EventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

