/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets EventType
 */
public enum EventType {
  
  USER_SIGNED_UP("userSignedUp"),
  
  USER_SIGNED_IN("userSignedIn"),
  
  USER_SIGNED_OUT("userSignedOut"),
  
  TAB_OPENED("tabOpened"),
  
  TAB_URL_CHANGED("tabUrlChanged"),
  
  TAB_VISIBILITY_CHANGED("tabVisibilityChanged"),
  
  LOCATION_DETECTED("locationDetected"),
  
  CLIENT_DETECTED("clientDetected"),
  
  PAGE_OPENED("pageOpened"),
  
  PAGE_LOADED("pageLoaded"),
  
  PRODUCT_VIEWED("productViewed"),
  
  CART_VIEWED("cartViewed"),
  
  CART_MODIFIED("cartModified"),
  
  CHECKOUT_STARTED("checkoutStarted"),
  
  ORDER_PLACED("orderPlaced"),
  
  TEST_GROUP_ASSIGNED("testGroupAssigned"),
  
  NOTHING_CHANGED("nothingChanged"),
  
  GOAL_COMPLETED("goalCompleted"),
  
  EVENT_OCCURRED("eventOccurred");

  private String value;

  EventType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EventType fromValue(String value) {
    for (EventType b : EventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

