/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.Currency;
import com.croct.client.export.model.GeoPoint;
import com.croct.client.export.model.LocationContinent;
import com.croct.client.export.model.LocationSource;
import com.croct.client.export.model.Region;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * An identification or estimation of a geographic location of an object.
 */
@JsonPropertyOrder({
  Location.JSON_PROPERTY_CONTINENT,
  Location.JSON_PROPERTY_COUNTRY,
  Location.JSON_PROPERTY_REGION,
  Location.JSON_PROPERTY_CITY,
  Location.JSON_PROPERTY_DISTRICT,
  Location.JSON_PROPERTY_TIMEZONE,
  Location.JSON_PROPERTY_COORDINATES,
  Location.JSON_PROPERTY_CURRENCY,
  Location.JSON_PROPERTY_PHONE_CODE,
  Location.JSON_PROPERTY_POPULATION,
  Location.JSON_PROPERTY_POSTAL_CODE,
  Location.JSON_PROPERTY_LANGUAGES,
  Location.JSON_PROPERTY_TAGS,
  Location.JSON_PROPERTY_SOURCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class Location {
  public static final String JSON_PROPERTY_CONTINENT = "continent";
  @javax.annotation.Nullable
  private LocationContinent continent;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_REGION = "region";
  @javax.annotation.Nonnull
  private Region region;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_DISTRICT = "district";
  @javax.annotation.Nullable
  private String district;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @javax.annotation.Nullable
  private String timezone;

  public static final String JSON_PROPERTY_COORDINATES = "coordinates";
  @javax.annotation.Nullable
  private GeoPoint coordinates;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private JsonNullable<Currency> currency = JsonNullable.<Currency>undefined();

  public static final String JSON_PROPERTY_PHONE_CODE = "phoneCode";
  private JsonNullable<String> phoneCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_POPULATION = "population";
  private JsonNullable<String> population = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private JsonNullable<String> postalCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LANGUAGES = "languages";
  @javax.annotation.Nullable
  private List<String> languages = new ArrayList<>();

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nullable
  private LocationSource source;

  public Location() { 
  }

  public Location continent(@javax.annotation.Nullable LocationContinent continent) {
    this.continent = continent;
    return this;
  }

  /**
   * Get continent
   * @return continent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTINENT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationContinent getContinent() {
    return continent;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTINENT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContinent(@javax.annotation.Nullable LocationContinent continent) {
    this.continent = continent;
  }


  public Location country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * The highest administrative division, also known as a nation. The value is a two-letter country code, as defined in ISO 3166. For example, US for United States, BR for Brazil and DE for Germany.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public Location region(@javax.annotation.Nonnull Region region) {
    this.region = region;
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REGION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Region getRegion() {
    return region;
  }


  @JsonProperty(value = JSON_PROPERTY_REGION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegion(@javax.annotation.Nonnull Region region) {
    this.region = region;
  }


  public Location city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * The name of the incorporated city or town political entity. For example, \&quot;Sao Paulo\&quot;.
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCity() {
    return city;
  }


  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public Location district(@javax.annotation.Nullable String district) {
    this.district = district;
    return this;
  }

  /**
   * An administrative division smaller than a city and larger than a neighborhood. For example, the district of Manhattan in New York.
   * @return district
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTRICT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDistrict() {
    return district;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTRICT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDistrict(@javax.annotation.Nullable String district) {
    this.district = district;
  }


  public Location timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * The time-zone ID as defined in IANA Time Zone Database. For example, \&quot;America/New_York\&quot;.
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public Location coordinates(@javax.annotation.Nullable GeoPoint coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * Get coordinates
   * @return coordinates
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COORDINATES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GeoPoint getCoordinates() {
    return coordinates;
  }


  @JsonProperty(value = JSON_PROPERTY_COORDINATES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoordinates(@javax.annotation.Nullable GeoPoint coordinates) {
    this.coordinates = coordinates;
  }


  public Location currency(@javax.annotation.Nullable Currency currency) {
    this.currency = JsonNullable.<Currency>of(currency);
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Currency getCurrency() {
        return currency.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Currency> getCurrency_JsonNullable() {
    return currency;
  }
  
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  public void setCurrency_JsonNullable(JsonNullable<Currency> currency) {
    this.currency = currency;
  }

  public void setCurrency(@javax.annotation.Nullable Currency currency) {
    this.currency = JsonNullable.<Currency>of(currency);
  }


  public Location phoneCode(@javax.annotation.Nullable String phoneCode) {
    this.phoneCode = JsonNullable.<String>of(phoneCode);
    return this;
  }

  /**
   * The international dialing code for this location. For example, &#39;+1&#39; or &#39;+55&#39;.
   * @return phoneCode
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPhoneCode() {
        return phoneCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PHONE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPhoneCode_JsonNullable() {
    return phoneCode;
  }
  
  @JsonProperty(JSON_PROPERTY_PHONE_CODE)
  public void setPhoneCode_JsonNullable(JsonNullable<String> phoneCode) {
    this.phoneCode = phoneCode;
  }

  public void setPhoneCode(@javax.annotation.Nullable String phoneCode) {
    this.phoneCode = JsonNullable.<String>of(phoneCode);
  }


  public Location population(@javax.annotation.Nullable String population) {
    this.population = JsonNullable.<String>of(population);
    return this;
  }

  /**
   * The approximate number of people living within the borders of the represented location.
   * @return population
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPopulation() {
        return population.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_POPULATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPopulation_JsonNullable() {
    return population;
  }
  
  @JsonProperty(JSON_PROPERTY_POPULATION)
  public void setPopulation_JsonNullable(JsonNullable<String> population) {
    this.population = population;
  }

  public void setPopulation(@javax.annotation.Nullable String population) {
    this.population = JsonNullable.<String>of(population);
  }


  public Location postalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = JsonNullable.<String>of(postalCode);
    return this;
  }

  /**
   * The general postal code for the location, such as a starting range, but it may also represent another relevant code for the area. For example, &#39;12345-678&#39;.
   * @return postalCode
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPostalCode() {
        return postalCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_POSTAL_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPostalCode_JsonNullable() {
    return postalCode;
  }
  
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  public void setPostalCode_JsonNullable(JsonNullable<String> postalCode) {
    this.postalCode = postalCode;
  }

  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = JsonNullable.<String>of(postalCode);
  }


  public Location languages(@javax.annotation.Nullable List<String> languages) {
    this.languages = languages;
    return this;
  }

  public Location addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<>();
    }
    this.languages.add(languagesItem);
    return this;
  }

  /**
   * A list of locales following the ISO 639-1 and ISO 3166-1 standards, representing the languages spoken in the location, ordered from the most spoken to the least spoken. For example, &#39;pt-br&#39; or &#39;en-us&#39;.
   * @return languages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LANGUAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getLanguages() {
    return languages;
  }


  @JsonProperty(value = JSON_PROPERTY_LANGUAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguages(@javax.annotation.Nullable List<String> languages) {
    this.languages = languages;
  }


  public Location tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Location addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * A list of tags addressing different aspects of a location. For example, &#39;beach&#39; or &#39;ocean&#39;.
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public Location source(@javax.annotation.Nullable LocationSource source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationSource getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@javax.annotation.Nullable LocationSource source) {
    this.source = source;
  }


  /**
   * Return true if this Location object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    sb.append("    continent: ").append(toIndentedString(continent)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    phoneCode: ").append(toIndentedString(phoneCode)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

