/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.1
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * A position in a two-dimensional space.
 */
@JsonPropertyOrder({
  Point.JSON_PROPERTY_X,
  Point.JSON_PROPERTY_Y
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0-SNAPSHOT")
public class Point {
  public static final String JSON_PROPERTY_X = "x";
  @javax.annotation.Nonnull
  private Integer x;

  public static final String JSON_PROPERTY_Y = "y";
  @javax.annotation.Nonnull
  private Integer y;

  public Point() { 
  }

  public Point x(@javax.annotation.Nonnull Integer x) {
    this.x = x;
    return this;
  }

  /**
   * The horizontal position in pixels.
   * @return x
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_X, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getX() {
    return x;
  }


  @JsonProperty(value = JSON_PROPERTY_X, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setX(@javax.annotation.Nonnull Integer x) {
    this.x = x;
  }


  public Point y(@javax.annotation.Nonnull Integer y) {
    this.y = y;
    return this;
  }

  /**
   * The vertical position in pixels.
   * @return y
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_Y, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getY() {
    return y;
  }


  @JsonProperty(value = JSON_PROPERTY_Y, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setY(@javax.annotation.Nonnull Integer y) {
    this.y = y;
  }


  /**
   * Return true if this Point object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Point {\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

