/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * The detailed information of a post.
 */
@JsonPropertyOrder({
  PostDetails.JSON_PROPERTY_POST_ID,
  PostDetails.JSON_PROPERTY_URL,
  PostDetails.JSON_PROPERTY_TITLE,
  PostDetails.JSON_PROPERTY_TAGS,
  PostDetails.JSON_PROPERTY_CATEGORIES,
  PostDetails.JSON_PROPERTY_AUTHORS,
  PostDetails.JSON_PROPERTY_PUBLISH_TIME,
  PostDetails.JSON_PROPERTY_UPDATE_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0-SNAPSHOT")
public class PostDetails {
  public static final String JSON_PROPERTY_POST_ID = "postId";
  @javax.annotation.Nonnull
  private String postId;

  public static final String JSON_PROPERTY_URL = "url";
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nonnull
  private String title;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<String>> tags = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  private JsonNullable<List<String>> categories = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_AUTHORS = "authors";
  @javax.annotation.Nullable
  private List<String> authors = new ArrayList<>();

  public static final String JSON_PROPERTY_PUBLISH_TIME = "publishTime";
  @javax.annotation.Nonnull
  private Long publishTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "updateTime";
  private JsonNullable<Long> updateTime = JsonNullable.<Long>undefined();

  public PostDetails() { 
  }

  public PostDetails postId(@javax.annotation.Nonnull String postId) {
    this.postId = postId;
    return this;
  }

  /**
   * The ID that uniquely identifies the post.
   * @return postId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPostId() {
    return postId;
  }


  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPostId(@javax.annotation.Nonnull String postId) {
    this.postId = postId;
  }


  public PostDetails url(@javax.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    return this;
  }

  /**
   * The URL of the post page.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }


  public PostDetails title(@javax.annotation.Nonnull String title) {
    this.title = title;
    return this;
  }

  /**
   * The title of the post, non-empty.
   * @return title
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(@javax.annotation.Nonnull String title) {
    this.title = title;
  }


  public PostDetails tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
    return this;
  }

  public PostDetails addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * The set of post tags.
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
  }


  public PostDetails categories(@javax.annotation.Nullable List<String> categories) {
    this.categories = JsonNullable.<List<String>>of(categories);
    return this;
  }

  public PostDetails addCategoriesItem(String categoriesItem) {
    if (this.categories == null || !this.categories.isPresent()) {
      this.categories = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.categories.get().add(categoriesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * The categories the post belongs to.
   * @return categories
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getCategories() {
        return categories.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getCategories_JsonNullable() {
    return categories;
  }
  
  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  public void setCategories_JsonNullable(JsonNullable<List<String>> categories) {
    this.categories = categories;
  }

  public void setCategories(@javax.annotation.Nullable List<String> categories) {
    this.categories = JsonNullable.<List<String>>of(categories);
  }


  public PostDetails authors(@javax.annotation.Nullable List<String> authors) {
    this.authors = authors;
    return this;
  }

  public PostDetails addAuthorsItem(String authorsItem) {
    if (this.authors == null) {
      this.authors = new ArrayList<>();
    }
    this.authors.add(authorsItem);
    return this;
  }

  /**
   * The authors of the post.
   * @return authors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTHORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAuthors() {
    return authors;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthors(@javax.annotation.Nullable List<String> authors) {
    this.authors = authors;
  }


  public PostDetails publishTime(@javax.annotation.Nonnull Long publishTime) {
    this.publishTime = publishTime;
    return this;
  }

  /**
   * The timestamp of the post publication, in milliseconds since epoch.
   * @return publishTime
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PUBLISH_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPublishTime() {
    return publishTime;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLISH_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublishTime(@javax.annotation.Nonnull Long publishTime) {
    this.publishTime = publishTime;
  }


  public PostDetails updateTime(@javax.annotation.Nullable Long updateTime) {
    this.updateTime = JsonNullable.<Long>of(updateTime);
    return this;
  }

  /**
   * The timestamp of the post&#39;s last update, in milliseconds since epoch.
   * @return updateTime
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Long getUpdateTime() {
        return updateTime.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getUpdateTime_JsonNullable() {
    return updateTime;
  }
  
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  public void setUpdateTime_JsonNullable(JsonNullable<Long> updateTime) {
    this.updateTime = updateTime;
  }

  public void setUpdateTime(@javax.annotation.Nullable Long updateTime) {
    this.updateTime = JsonNullable.<Long>of(updateTime);
  }


  /**
   * Return true if this PostDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostDetails {\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    authors: ").append(toIndentedString(authors)).append("\n");
    sb.append("    publishTime: ").append(toIndentedString(publishTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

