/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * The detailed information of a product.
 */
@JsonPropertyOrder({
  ProductDetails.JSON_PROPERTY_PRODUCT_ID,
  ProductDetails.JSON_PROPERTY_SKU,
  ProductDetails.JSON_PROPERTY_NAME,
  ProductDetails.JSON_PROPERTY_CATEGORY,
  ProductDetails.JSON_PROPERTY_BRAND,
  ProductDetails.JSON_PROPERTY_VARIANT,
  ProductDetails.JSON_PROPERTY_DISPLAY_PRICE,
  ProductDetails.JSON_PROPERTY_ORIGINAL_PRICE,
  ProductDetails.JSON_PROPERTY_URL,
  ProductDetails.JSON_PROPERTY_IMAGE_URL
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class ProductDetails {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  @javax.annotation.Nonnull
  private String productId;

  public static final String JSON_PROPERTY_SKU = "sku";
  @javax.annotation.Nullable
  private String sku;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  @javax.annotation.Nullable
  private String category;

  public static final String JSON_PROPERTY_BRAND = "brand";
  @javax.annotation.Nullable
  private String brand;

  public static final String JSON_PROPERTY_VARIANT = "variant";
  @javax.annotation.Nullable
  private String variant;

  public static final String JSON_PROPERTY_DISPLAY_PRICE = "displayPrice";
  @javax.annotation.Nonnull
  private Double displayPrice;

  public static final String JSON_PROPERTY_ORIGINAL_PRICE = "originalPrice";
  @javax.annotation.Nullable
  private Double originalPrice;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_IMAGE_URL = "imageUrl";
  @javax.annotation.Nullable
  private String imageUrl;

  public ProductDetails() { 
  }

  public ProductDetails productId(@javax.annotation.Nonnull String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * The ID that uniquely identifies the product across the store, non-empty. For example, \&quot;3108\&quot; or \&quot;yO7q4r\&quot;.
   * @return productId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(@javax.annotation.Nonnull String productId) {
    this.productId = productId;
  }


  public ProductDetails sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * The code that uniquely identifies the product variant across the store, non-empty. For example, \&quot;IPH-GRE-64\&quot;.
   * @return sku
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SKU, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSku() {
    return sku;
  }


  @JsonProperty(value = JSON_PROPERTY_SKU, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public ProductDetails name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the product, non-empty. For example \&quot;iPhone\&quot;.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ProductDetails category(@javax.annotation.Nullable String category) {
    this.category = category;
    return this;
  }

  /**
   * The category of the product, non-empty. For example, \&quot;Phone\&quot;.
   * @return category
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategory(@javax.annotation.Nullable String category) {
    this.category = category;
  }


  public ProductDetails brand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
    return this;
  }

  /**
   * The brand associated with the product. For example, \&quot;Apple\&quot;.
   * @return brand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBrand() {
    return brand;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBrand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
  }


  public ProductDetails variant(@javax.annotation.Nullable String variant) {
    this.variant = variant;
    return this;
  }

  /**
   * The variant of the product, such as size, color and style. For example, \&quot;64GB Green\&quot;.
   * @return variant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVariant() {
    return variant;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVariant(@javax.annotation.Nullable String variant) {
    this.variant = variant;
  }


  public ProductDetails displayPrice(@javax.annotation.Nonnull Double displayPrice) {
    this.displayPrice = displayPrice;
    return this;
  }

  /**
   * The price of the product displayed in the store. For example, 59.90.
   * @return displayPrice
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_PRICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getDisplayPrice() {
    return displayPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_PRICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayPrice(@javax.annotation.Nonnull Double displayPrice) {
    this.displayPrice = displayPrice;
  }


  public ProductDetails originalPrice(@javax.annotation.Nullable Double originalPrice) {
    this.originalPrice = originalPrice;
    return this;
  }

  /**
   * The original price of the product. For example, 99.90.
   * @return originalPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getOriginalPrice() {
    return originalPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginalPrice(@javax.annotation.Nullable Double originalPrice) {
    this.originalPrice = originalPrice;
  }


  public ProductDetails url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * The URL of the product page. For example, \&quot;https://apple.com/iphone\&quot;.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public ProductDetails imageUrl(@javax.annotation.Nullable String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * The URL of the main product image. For example, \&quot;https://img.apple.com/iphone.png\&quot;.
   * @return imageUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getImageUrl() {
    return imageUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setImageUrl(@javax.annotation.Nullable String imageUrl) {
    this.imageUrl = imageUrl;
  }


  /**
   * Return true if this ProductDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDetails {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    displayPrice: ").append(toIndentedString(displayPrice)).append("\n");
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

