/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.Campaign;
import com.croct.client.export.model.Location;
import com.croct.client.export.model.SessionStatistics;
import com.croct.client.export.model.SessionWindow;
import com.croct.client.export.model.WebClient;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * Session
 */
@JsonPropertyOrder({
  Session.JSON_PROPERTY_SESSION_ID,
  Session.JSON_PROPERTY_USER_ID,
  Session.JSON_PROPERTY_PARENT_ID,
  Session.JSON_PROPERTY_EXTERNAL_USER_ID,
  Session.JSON_PROPERTY_WINDOW,
  Session.JSON_PROPERTY_CLOSE_TIME,
  Session.JSON_PROPERTY_REFERRER,
  Session.JSON_PROPERTY_LANDING_PAGE_URL,
  Session.JSON_PROPERTY_CAMPAIGN,
  Session.JSON_PROPERTY_LOCATION,
  Session.JSON_PROPERTY_CLIENT,
  Session.JSON_PROPERTY_ATTRIBUTES,
  Session.JSON_PROPERTY_STATISTICS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class Session {
  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private UUID sessionId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private UUID userId;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  private JsonNullable<UUID> parentId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_USER_ID = "externalUserId";
  private JsonNullable<String> externalUserId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WINDOW = "window";
  @javax.annotation.Nullable
  private SessionWindow window;

  public static final String JSON_PROPERTY_CLOSE_TIME = "closeTime";
  @javax.annotation.Nullable
  private Long closeTime;

  public static final String JSON_PROPERTY_REFERRER = "referrer";
  private JsonNullable<String> referrer = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LANDING_PAGE_URL = "landingPageUrl";
  private JsonNullable<String> landingPageUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CAMPAIGN = "campaign";
  @javax.annotation.Nullable
  private Campaign campaign;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nullable
  private Location location;

  public static final String JSON_PROPERTY_CLIENT = "client";
  @javax.annotation.Nullable
  private WebClient client;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @javax.annotation.Nullable
  private Map<String, Object> attributes = new HashMap<>();

  public static final String JSON_PROPERTY_STATISTICS = "statistics";
  @javax.annotation.Nullable
  private SessionStatistics statistics;

  public Session() { 
  }

  public Session sessionId(@javax.annotation.Nullable UUID sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * The ID that uniquely identifies the session across the application.
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable UUID sessionId) {
    this.sessionId = sessionId;
  }


  public Session userId(@javax.annotation.Nullable UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The ID that uniquely identifies the user across the workspace.
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable UUID userId) {
    this.userId = userId;
  }


  public Session parentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
    return this;
  }

  /**
   * The ID of the session that superseded this session. Usually, a session receives a parent ID when a user is identified, causing the current anonymous session to end and a new identified session to begin. In this case, the ID of the new session is assigned as the parent ID of the anonymous session.
   * @return parentId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public UUID getParentId() {
        return parentId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getParentId_JsonNullable() {
    return parentId;
  }
  
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  public void setParentId_JsonNullable(JsonNullable<UUID> parentId) {
    this.parentId = parentId;
  }

  public void setParentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
  }


  public Session externalUserId(@javax.annotation.Nullable String externalUserId) {
    this.externalUserId = JsonNullable.<String>of(externalUserId);
    return this;
  }

  /**
   * The external user ID that is used to identify the user on the application side, unique across the workspace. It is always null for anonymous users.
   * @return externalUserId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getExternalUserId() {
        return externalUserId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExternalUserId_JsonNullable() {
    return externalUserId;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTERNAL_USER_ID)
  public void setExternalUserId_JsonNullable(JsonNullable<String> externalUserId) {
    this.externalUserId = externalUserId;
  }

  public void setExternalUserId(@javax.annotation.Nullable String externalUserId) {
    this.externalUserId = JsonNullable.<String>of(externalUserId);
  }


  public Session window(@javax.annotation.Nullable SessionWindow window) {
    this.window = window;
    return this;
  }

  /**
   * Get window
   * @return window
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionWindow getWindow() {
    return window;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWindow(@javax.annotation.Nullable SessionWindow window) {
    this.window = window;
  }


  public Session closeTime(@javax.annotation.Nullable Long closeTime) {
    this.closeTime = closeTime;
    return this;
  }

  /**
   * The time from which the session is closed for new events, but still may accept late-arriving events. The close time may be extended if new events arrive before the session is closed.
   * @return closeTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLOSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCloseTime() {
    return closeTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CLOSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloseTime(@javax.annotation.Nullable Long closeTime) {
    this.closeTime = closeTime;
  }


  public Session referrer(@javax.annotation.Nullable String referrer) {
    this.referrer = JsonNullable.<String>of(referrer);
    return this;
  }

  /**
   * The URI of the content that linked to the page that started the session.
   * @return referrer
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getReferrer() {
        return referrer.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REFERRER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReferrer_JsonNullable() {
    return referrer;
  }
  
  @JsonProperty(JSON_PROPERTY_REFERRER)
  public void setReferrer_JsonNullable(JsonNullable<String> referrer) {
    this.referrer = referrer;
  }

  public void setReferrer(@javax.annotation.Nullable String referrer) {
    this.referrer = JsonNullable.<String>of(referrer);
  }


  public Session landingPageUrl(@javax.annotation.Nullable String landingPageUrl) {
    this.landingPageUrl = JsonNullable.<String>of(landingPageUrl);
    return this;
  }

  /**
   * The page that started the session.
   * @return landingPageUrl
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLandingPageUrl() {
        return landingPageUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LANDING_PAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLandingPageUrl_JsonNullable() {
    return landingPageUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_LANDING_PAGE_URL)
  public void setLandingPageUrl_JsonNullable(JsonNullable<String> landingPageUrl) {
    this.landingPageUrl = landingPageUrl;
  }

  public void setLandingPageUrl(@javax.annotation.Nullable String landingPageUrl) {
    this.landingPageUrl = JsonNullable.<String>of(landingPageUrl);
  }


  public Session campaign(@javax.annotation.Nullable Campaign campaign) {
    this.campaign = campaign;
    return this;
  }

  /**
   * Get campaign
   * @return campaign
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Campaign getCampaign() {
    return campaign;
  }


  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaign(@javax.annotation.Nullable Campaign campaign) {
    this.campaign = campaign;
  }


  public Session location(@javax.annotation.Nullable Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Location getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@javax.annotation.Nullable Location location) {
    this.location = location;
  }


  public Session client(@javax.annotation.Nullable WebClient client) {
    this.client = client;
    return this;
  }

  /**
   * Get client
   * @return client
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WebClient getClient() {
    return client;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClient(@javax.annotation.Nullable WebClient client) {
    this.client = client;
  }


  public Session attributes(@javax.annotation.Nullable Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Session putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

  /**
   * The custom attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getAttributes() {
    return attributes;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributes(@javax.annotation.Nullable Map<String, Object> attributes) {
    this.attributes = attributes;
  }


  public Session statistics(@javax.annotation.Nullable SessionStatistics statistics) {
    this.statistics = statistics;
    return this;
  }

  /**
   * Get statistics
   * @return statistics
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATISTICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionStatistics getStatistics() {
    return statistics;
  }


  @JsonProperty(value = JSON_PROPERTY_STATISTICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatistics(@javax.annotation.Nullable SessionStatistics statistics) {
    this.statistics = statistics;
  }


  /**
   * Return true if this Session object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    externalUserId: ").append(toIndentedString(externalUserId)).append("\n");
    sb.append("    window: ").append(toIndentedString(window)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    landingPageUrl: ").append(toIndentedString(landingPageUrl)).append("\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

