/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.Session;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * SessionResponse
 */
@JsonPropertyOrder({
  SessionResponse.JSON_PROPERTY_ITEMS,
  SessionResponse.JSON_PROPERTY_NEXT_CURSOR
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class SessionResponse {
  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nonnull
  private List<Session> items = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_CURSOR = "nextCursor";
  @javax.annotation.Nonnull
  private String nextCursor;

  public SessionResponse() { 
  }

  public SessionResponse items(@javax.annotation.Nonnull List<Session> items) {
    this.items = items;
    return this;
  }

  public SessionResponse addItemsItem(Session itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Session> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(@javax.annotation.Nonnull List<Session> items) {
    this.items = items;
  }


  public SessionResponse nextCursor(@javax.annotation.Nonnull String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * Get nextCursor
   * @return nextCursor
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNextCursor() {
    return nextCursor;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextCursor(@javax.annotation.Nonnull String nextCursor) {
    this.nextCursor = nextCursor;
  }


  /**
   * Return true if this SessionResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionResponse {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

