/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.SlotPersonalizedMetadata;
import com.croct.client.export.model.SlotPersonalizedPersonalization;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * An event recording a slot personalization.
 */
@JsonPropertyOrder({
  SlotPersonalized.JSON_PROPERTY_AT_TYPE,
  SlotPersonalized.JSON_PROPERTY_PERSONALIZATION,
  SlotPersonalized.JSON_PROPERTY_METADATA
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class SlotPersonalized {
  public static final String JSON_PROPERTY_AT_TYPE = "@type";
  @javax.annotation.Nonnull
  private String atType;

  public static final String JSON_PROPERTY_PERSONALIZATION = "personalization";
  @javax.annotation.Nonnull
  private SlotPersonalizedPersonalization personalization;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nonnull
  private SlotPersonalizedMetadata metadata;

  public SlotPersonalized() { 
  }

  public SlotPersonalized atType(@javax.annotation.Nonnull String atType) {
    this.atType = atType;
    return this;
  }

  /**
   * The event type identifier.
   * @return atType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAtType() {
    return atType;
  }


  @JsonProperty(value = JSON_PROPERTY_AT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAtType(@javax.annotation.Nonnull String atType) {
    this.atType = atType;
  }


  public SlotPersonalized personalization(@javax.annotation.Nonnull SlotPersonalizedPersonalization personalization) {
    this.personalization = personalization;
    return this;
  }

  /**
   * Get personalization
   * @return personalization
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERSONALIZATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SlotPersonalizedPersonalization getPersonalization() {
    return personalization;
  }


  @JsonProperty(value = JSON_PROPERTY_PERSONALIZATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonalization(@javax.annotation.Nonnull SlotPersonalizedPersonalization personalization) {
    this.personalization = personalization;
  }


  public SlotPersonalized metadata(@javax.annotation.Nonnull SlotPersonalizedMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SlotPersonalizedMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@javax.annotation.Nonnull SlotPersonalizedMetadata metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this SlotPersonalized object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlotPersonalized {\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    personalization: ").append(toIndentedString(personalization)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

