/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.SlotPersonalizedPersonalizationAssignedVariant;
import com.croct.client.export.model.SlotPersonalizedPersonalizationSlotVersion;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * SlotPersonalizedPersonalization
 */
@JsonPropertyOrder({
  SlotPersonalizedPersonalization.JSON_PROPERTY_AUDIENCE_ID,
  SlotPersonalizedPersonalization.JSON_PROPERTY_SLOT_ID,
  SlotPersonalizedPersonalization.JSON_PROPERTY_EXPERIENCE_ID,
  SlotPersonalizedPersonalization.JSON_PROPERTY_CONTENT_ID,
  SlotPersonalizedPersonalization.JSON_PROPERTY_SLOT_VERSION,
  SlotPersonalizedPersonalization.JSON_PROPERTY_ASSIGNED_VARIANT
})
@JsonTypeName("SlotPersonalized_personalization")
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class SlotPersonalizedPersonalization {
  public static final String JSON_PROPERTY_AUDIENCE_ID = "audienceId";
  @javax.annotation.Nonnull
  private UUID audienceId;

  public static final String JSON_PROPERTY_SLOT_ID = "slotId";
  @javax.annotation.Nonnull
  private UUID slotId;

  public static final String JSON_PROPERTY_EXPERIENCE_ID = "experienceId";
  @javax.annotation.Nonnull
  private UUID experienceId;

  public static final String JSON_PROPERTY_CONTENT_ID = "contentId";
  @javax.annotation.Nonnull
  private UUID contentId;

  public static final String JSON_PROPERTY_SLOT_VERSION = "slotVersion";
  private JsonNullable<SlotPersonalizedPersonalizationSlotVersion> slotVersion = JsonNullable.<SlotPersonalizedPersonalizationSlotVersion>undefined();

  public static final String JSON_PROPERTY_ASSIGNED_VARIANT = "assignedVariant";
  @javax.annotation.Nullable
  private SlotPersonalizedPersonalizationAssignedVariant assignedVariant;

  public SlotPersonalizedPersonalization() { 
  }

  public SlotPersonalizedPersonalization audienceId(@javax.annotation.Nonnull UUID audienceId) {
    this.audienceId = audienceId;
    return this;
  }

  /**
   * The ID that uniquely identifies the audience.
   * @return audienceId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getAudienceId() {
    return audienceId;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudienceId(@javax.annotation.Nonnull UUID audienceId) {
    this.audienceId = audienceId;
  }


  public SlotPersonalizedPersonalization slotId(@javax.annotation.Nonnull UUID slotId) {
    this.slotId = slotId;
    return this;
  }

  /**
   * The ID that uniquely identifies the slot.
   * @return slotId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLOT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSlotId() {
    return slotId;
  }


  @JsonProperty(value = JSON_PROPERTY_SLOT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlotId(@javax.annotation.Nonnull UUID slotId) {
    this.slotId = slotId;
  }


  public SlotPersonalizedPersonalization experienceId(@javax.annotation.Nonnull UUID experienceId) {
    this.experienceId = experienceId;
    return this;
  }

  /**
   * The ID that uniquely identifies the experience.
   * @return experienceId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPERIENCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getExperienceId() {
    return experienceId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPERIENCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExperienceId(@javax.annotation.Nonnull UUID experienceId) {
    this.experienceId = experienceId;
  }


  public SlotPersonalizedPersonalization contentId(@javax.annotation.Nonnull UUID contentId) {
    this.contentId = contentId;
    return this;
  }

  /**
   * The ID that uniquely identifies the content.
   * @return contentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getContentId() {
    return contentId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentId(@javax.annotation.Nonnull UUID contentId) {
    this.contentId = contentId;
  }


  public SlotPersonalizedPersonalization slotVersion(@javax.annotation.Nullable SlotPersonalizedPersonalizationSlotVersion slotVersion) {
    this.slotVersion = JsonNullable.<SlotPersonalizedPersonalizationSlotVersion>of(slotVersion);
    return this;
  }

  /**
   * Get slotVersion
   * @return slotVersion
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public SlotPersonalizedPersonalizationSlotVersion getSlotVersion() {
        return slotVersion.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SLOT_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<SlotPersonalizedPersonalizationSlotVersion> getSlotVersion_JsonNullable() {
    return slotVersion;
  }
  
  @JsonProperty(JSON_PROPERTY_SLOT_VERSION)
  public void setSlotVersion_JsonNullable(JsonNullable<SlotPersonalizedPersonalizationSlotVersion> slotVersion) {
    this.slotVersion = slotVersion;
  }

  public void setSlotVersion(@javax.annotation.Nullable SlotPersonalizedPersonalizationSlotVersion slotVersion) {
    this.slotVersion = JsonNullable.<SlotPersonalizedPersonalizationSlotVersion>of(slotVersion);
  }


  public SlotPersonalizedPersonalization assignedVariant(@javax.annotation.Nullable SlotPersonalizedPersonalizationAssignedVariant assignedVariant) {
    this.assignedVariant = assignedVariant;
    return this;
  }

  /**
   * Get assignedVariant
   * @return assignedVariant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SlotPersonalizedPersonalizationAssignedVariant getAssignedVariant() {
    return assignedVariant;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssignedVariant(@javax.annotation.Nullable SlotPersonalizedPersonalizationAssignedVariant assignedVariant) {
    this.assignedVariant = assignedVariant;
  }


  /**
   * Return true if this SlotPersonalized_personalization object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlotPersonalizedPersonalization {\n");
    sb.append("    audienceId: ").append(toIndentedString(audienceId)).append("\n");
    sb.append("    slotId: ").append(toIndentedString(slotId)).append("\n");
    sb.append("    experienceId: ").append(toIndentedString(experienceId)).append("\n");
    sb.append("    contentId: ").append(toIndentedString(contentId)).append("\n");
    sb.append("    slotVersion: ").append(toIndentedString(slotVersion)).append("\n");
    sb.append("    assignedVariant: ").append(toIndentedString(assignedVariant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

