/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * Additional information about the personalization.
 */
@JsonPropertyOrder({
  SlotPersonalizedMetadata.JSON_PROPERTY_AUDIENCE_NAME,
  SlotPersonalizedMetadata.JSON_PROPERTY_AUDIENCE_CUSTOM_ID,
  SlotPersonalizedMetadata.JSON_PROPERTY_SLOT_NAME,
  SlotPersonalizedMetadata.JSON_PROPERTY_SLOT_CUSTOM_ID,
  SlotPersonalizedMetadata.JSON_PROPERTY_EXPERIENCE_NAME,
  SlotPersonalizedMetadata.JSON_PROPERTY_EXPERIMENT_NAME,
  SlotPersonalizedMetadata.JSON_PROPERTY_VARIANT_NAME
})
@JsonTypeName("SlotPersonalized_metadata")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class SlotPersonalizedMetadata {
  public static final String JSON_PROPERTY_AUDIENCE_NAME = "audienceName";
  @javax.annotation.Nullable
  private String audienceName;

  public static final String JSON_PROPERTY_AUDIENCE_CUSTOM_ID = "audienceCustomId";
  @javax.annotation.Nullable
  private String audienceCustomId;

  public static final String JSON_PROPERTY_SLOT_NAME = "slotName";
  @javax.annotation.Nullable
  private String slotName;

  public static final String JSON_PROPERTY_SLOT_CUSTOM_ID = "slotCustomId";
  @javax.annotation.Nullable
  private String slotCustomId;

  public static final String JSON_PROPERTY_EXPERIENCE_NAME = "experienceName";
  @javax.annotation.Nullable
  private String experienceName;

  public static final String JSON_PROPERTY_EXPERIMENT_NAME = "experimentName";
  @javax.annotation.Nullable
  private String experimentName;

  public static final String JSON_PROPERTY_VARIANT_NAME = "variantName";
  @javax.annotation.Nullable
  private String variantName;

  public SlotPersonalizedMetadata() { 
  }

  public SlotPersonalizedMetadata audienceName(@javax.annotation.Nullable String audienceName) {
    this.audienceName = audienceName;
    return this;
  }

  /**
   * The name of the audience.
   * @return audienceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAudienceName() {
    return audienceName;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudienceName(@javax.annotation.Nullable String audienceName) {
    this.audienceName = audienceName;
  }


  public SlotPersonalizedMetadata audienceCustomId(@javax.annotation.Nullable String audienceCustomId) {
    this.audienceCustomId = audienceCustomId;
    return this;
  }

  /**
   * The custom ID of the audience.
   * @return audienceCustomId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_CUSTOM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAudienceCustomId() {
    return audienceCustomId;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_CUSTOM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudienceCustomId(@javax.annotation.Nullable String audienceCustomId) {
    this.audienceCustomId = audienceCustomId;
  }


  public SlotPersonalizedMetadata slotName(@javax.annotation.Nullable String slotName) {
    this.slotName = slotName;
    return this;
  }

  /**
   * The name of the slot.
   * @return slotName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SLOT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlotName() {
    return slotName;
  }


  @JsonProperty(value = JSON_PROPERTY_SLOT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlotName(@javax.annotation.Nullable String slotName) {
    this.slotName = slotName;
  }


  public SlotPersonalizedMetadata slotCustomId(@javax.annotation.Nullable String slotCustomId) {
    this.slotCustomId = slotCustomId;
    return this;
  }

  /**
   * The custom ID of the slot.
   * @return slotCustomId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SLOT_CUSTOM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlotCustomId() {
    return slotCustomId;
  }


  @JsonProperty(value = JSON_PROPERTY_SLOT_CUSTOM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlotCustomId(@javax.annotation.Nullable String slotCustomId) {
    this.slotCustomId = slotCustomId;
  }


  public SlotPersonalizedMetadata experienceName(@javax.annotation.Nullable String experienceName) {
    this.experienceName = experienceName;
    return this;
  }

  /**
   * The name of the experience.
   * @return experienceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPERIENCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExperienceName() {
    return experienceName;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPERIENCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExperienceName(@javax.annotation.Nullable String experienceName) {
    this.experienceName = experienceName;
  }


  public SlotPersonalizedMetadata experimentName(@javax.annotation.Nullable String experimentName) {
    this.experimentName = experimentName;
    return this;
  }

  /**
   * The name of the experiment.
   * @return experimentName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPERIMENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExperimentName() {
    return experimentName;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPERIMENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExperimentName(@javax.annotation.Nullable String experimentName) {
    this.experimentName = experimentName;
  }


  public SlotPersonalizedMetadata variantName(@javax.annotation.Nullable String variantName) {
    this.variantName = variantName;
    return this;
  }

  /**
   * The name of the variant.
   * @return variantName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVariantName() {
    return variantName;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVariantName(@javax.annotation.Nullable String variantName) {
    this.variantName = variantName;
  }


  /**
   * Return true if this SlotPersonalized_metadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlotPersonalizedMetadata {\n");
    sb.append("    audienceName: ").append(toIndentedString(audienceName)).append("\n");
    sb.append("    audienceCustomId: ").append(toIndentedString(audienceCustomId)).append("\n");
    sb.append("    slotName: ").append(toIndentedString(slotName)).append("\n");
    sb.append("    slotCustomId: ").append(toIndentedString(slotCustomId)).append("\n");
    sb.append("    experienceName: ").append(toIndentedString(experienceName)).append("\n");
    sb.append("    experimentName: ").append(toIndentedString(experimentName)).append("\n");
    sb.append("    variantName: ").append(toIndentedString(variantName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

