/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * SlotPersonalizedPersonalizationSlotVersion
 */
@JsonPropertyOrder({
  SlotPersonalizedPersonalizationSlotVersion.JSON_PROPERTY_MAJOR_VERSION,
  SlotPersonalizedPersonalizationSlotVersion.JSON_PROPERTY_MINOR_VERSION
})
@JsonTypeName("SlotPersonalized_personalization_slotVersion")
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class SlotPersonalizedPersonalizationSlotVersion {
  public static final String JSON_PROPERTY_MAJOR_VERSION = "majorVersion";
  @javax.annotation.Nullable
  private String majorVersion;

  public static final String JSON_PROPERTY_MINOR_VERSION = "minorVersion";
  @javax.annotation.Nullable
  private String minorVersion;

  public SlotPersonalizedPersonalizationSlotVersion() { 
  }

  public SlotPersonalizedPersonalizationSlotVersion majorVersion(@javax.annotation.Nullable String majorVersion) {
    this.majorVersion = majorVersion;
    return this;
  }

  /**
   * The major version.
   * @return majorVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAJOR_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMajorVersion() {
    return majorVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_MAJOR_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMajorVersion(@javax.annotation.Nullable String majorVersion) {
    this.majorVersion = majorVersion;
  }


  public SlotPersonalizedPersonalizationSlotVersion minorVersion(@javax.annotation.Nullable String minorVersion) {
    this.minorVersion = minorVersion;
    return this;
  }

  /**
   * The minor version.
   * @return minorVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MINOR_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMinorVersion() {
    return minorVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_MINOR_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinorVersion(@javax.annotation.Nullable String minorVersion) {
    this.minorVersion = minorVersion;
  }


  /**
   * Return true if this SlotPersonalized_personalization_slotVersion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlotPersonalizedPersonalizationSlotVersion {\n");
    sb.append("    majorVersion: ").append(toIndentedString(majorVersion)).append("\n");
    sb.append("    minorVersion: ").append(toIndentedString(minorVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

