/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * The aggregated statistics of the user.
 */
@JsonPropertyOrder({
  UserStatistics.JSON_PROPERTY_ORDERS,
  UserStatistics.JSON_PROPERTY_SESSIONS
})
@JsonTypeName("User_statistics")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0-SNAPSHOT")
public class UserStatistics {
  public static final String JSON_PROPERTY_ORDERS = "orders";
  @javax.annotation.Nullable
  private Integer orders;

  public static final String JSON_PROPERTY_SESSIONS = "sessions";
  @javax.annotation.Nullable
  private Integer sessions;

  public UserStatistics() { 
  }

  public UserStatistics orders(@javax.annotation.Nullable Integer orders) {
    this.orders = orders;
    return this;
  }

  /**
   * The total number of orders placed across all applications in a workspace.
   * @return orders
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrders() {
    return orders;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrders(@javax.annotation.Nullable Integer orders) {
    this.orders = orders;
  }


  public UserStatistics sessions(@javax.annotation.Nullable Integer sessions) {
    this.sessions = sessions;
    return this;
  }

  /**
   * The total number of sessions across all applications in a workspace.
   * @return sessions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSessions() {
    return sessions;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessions(@javax.annotation.Nullable Integer sessions) {
    this.sessions = sessions;
  }


  /**
   * Return true if this User_statistics object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserStatistics {\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

