/*
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.croct.client.export.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.croct.client.export.model.Browser;
import com.croct.client.export.model.Device;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.croct.client.export.JSON;


/**
 * The available information about a web client.
 */
@JsonPropertyOrder({
  WebClient.JSON_PROPERTY_BROWSER,
  WebClient.JSON_PROPERTY_DEVICE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class WebClient {
  public static final String JSON_PROPERTY_BROWSER = "browser";
  @javax.annotation.Nonnull
  private Browser browser;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @javax.annotation.Nonnull
  private Device device;

  public WebClient() { 
  }

  public WebClient browser(@javax.annotation.Nonnull Browser browser) {
    this.browser = browser;
    return this;
  }

  /**
   * Get browser
   * @return browser
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BROWSER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Browser getBrowser() {
    return browser;
  }


  @JsonProperty(value = JSON_PROPERTY_BROWSER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBrowser(@javax.annotation.Nonnull Browser browser) {
    this.browser = browser;
  }


  public WebClient device(@javax.annotation.Nonnull Device device) {
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Device getDevice() {
    return device;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDevice(@javax.annotation.Nonnull Device device) {
    this.device = device;
  }


  /**
   * Return true if this WebClient object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebClient {\n");
    sb.append("    browser: ").append(toIndentedString(browser)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

